// ... imports ...

import 'package:jaguar_orm/jaguar_orm.dart';

part 'deneme.jorm.dart';

class User {
  @PrimaryKey(auto: true, isNullable: false)
  int id;

  String name;

  int age;

  User({this.id, this.name, this.age});
}

/// Bean logic is generated by Jaguar ORM
@GenBean()
class UserBean extends Bean<User> with _UserBean {
  UserBean(Adapter adapter) : super(adapter);

  String get tableName => 'simple_user';
}